require_relative 'creature_animations/index'
require_relative 'projectile_animations/index'
require_relative 'on_target_animations/index'
require_relative 'projectiles/index'
require_relative 'red_ball'
require_relative 'slime_mud'
